---
- name: GATHER INPUT FROM SOURCE OF TRUTH
  include_tasks: "{{ sot }}.yaml"
  when: archive_dir is defined
  delegate_to: localhost
  run_once: yes


- name: ENSURE THAT THE DIR TO STORE RUNNING CONFIGS EXITS
  file:
    path: "{{ role_path }}/files/running_configs"
    state: directory
    mode: 0777
  delegate_to: localhost
  run_once: yes


- name: GET THE RUNNING CONFIG OF THE DEVICES
  cli:
    command: "show running"
  register: running_config

- name: SAVE THE RUNNING CONFIG LOCALLY
  template:
    src: render_running.j2
    dest: "{{ role_path }}/files/running_configs/{{ inventory_hostname }}.cfg"


- name: SANITIZE THE RUNNING CONFIGS
  lineinfile:
    regexp: "! Last configuration .*"
    path: "{{ role_path }}/files/running_configs/{{ inventory_hostname }}.cfg"
    state: absent

- name: REMOVE NON CONFIG LINES
  lineinfile:
    path: "{{ role_path }}/files/running_configs/{{ inventory_hostname }}.cfg"
    line: "Building configuration..."
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{ role_path }}/files/running_configs/{{ inventory_hostname }}.cfg"
    regexp: 'Current configuration.*'
    state: absent



- name: CHECK IF OOB CHANGES EXIST
  command: >-
    diff "{{ role_path }}"/files/running_configs "{{ role_path }}"/files/repo_dir/"{{ archive_dir }}"
  register: difference
  failed_when: difference.rc > 1
  changed_when: difference.rc == 1
  delegate_to: localhost
  run_once: true

- name: DISPLAY DIFFERENCES
  debug:
    var: difference.stdout
  when: difference.rc != 0
  delegate_to: localhost
  run_once: true


- name: TASKS IF AN OOB CHANGE IS DETECTED
  include_tasks: oob.yaml
  when: difference.rc != 0
  delegate_to: localhost
  run_once: true


- meta: end_play
  when: difference.rc != 0
