---
- name: GATHER INPUT FROM SOURCE OF TRUTH
  include_tasks: "{{ sot }}.yaml"
  when: archive_dir is defined
  delegate_to: localhost
  run_once: yes


- name: ENSURE THAT THE DIR TO STORE RUNNING CONFIGS EXITS
  file:
    path: "{{ role_path }}/files/running_configs"
    state: directory
    mode: 0777
  delegate_to: localhost
  run_once: yes


- name: GET THE RUNNING CONFIG OF THE DEVICES
  cli:
    command: "show running"
  register: running_config

- name: SAVE THE RUNNING CONFIG LOCALLY
  template:
    src: render_running.j2
    dest: "{{ role_path }}/files/running_configs/{{ inventory_hostname }}.cfg"


- name: CHECK IF OOB CHANGES EXIST
  command: >-
    diff "{{ role_path }}"/files/running_configs "{{ role_path }}"/files/repo_dir/"{{ archive_dir }}"
  register: difference
  failed_when: difference.rc > 1
  changed_when: difference.rc == 1
  delegate_to: localhost
  run_once: true

- name: DISPLAY DIFFERENCES
  debug:
    var: difference.stdout
  when: difference.rc != 0
  delegate_to: localhost
  run_once: true

- name: GENERATE DIFF REPORT
  template:
    src: diff_report.j2
    dest: "{{ role_path }}/files/diff_report.txt"
  when: difference.rc != 0
  delegate_to: localhost
  run_once: true

- name: STOP PLAY EXECUTION
  assert:
    that: difference.rc == 0
    msg: "Caretaker has identified an OOB change on your network. Manual sync required... Aborting deployment."
  delegate_to: localhost
  run_once: true
